apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: tns-db
    app.kubernetes.io/name: tns-db
    app.kubernetes.io/version: latest
  name: tns-db
  namespace: tns
spec:
  ports:
  - name: http-metrics
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: tns-db
    app.kubernetes.io/name: tns-db
