apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: tns-db
    app.kubernetes.io/name: tns-db
    app.kubernetes.io/version: latest
  name: tns-db
  namespace: tns
