apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: tns-app
    app.kubernetes.io/name: tns-app
    app.kubernetes.io/version: latest
  name: tns-app
  namespace: tns
