apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: loadgen
    app.kubernetes.io/instance: tns-loadgen
    app.kubernetes.io/name: tns-loadgen
    app.kubernetes.io/version: latest
  name: tns-loadgen
  namespace: tns
