apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: db
    app.kubernetes.io/instance: tns-db
    app.kubernetes.io/name: tns-db
    app.kubernetes.io/version: latest
  name: tns-db
  namespace: tns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: db
      app.kubernetes.io/instance: tns-db
      app.kubernetes.io/name: tns-db
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db
        app.kubernetes.io/instance: tns-db
        app.kubernetes.io/name: tns-db
        app.kubernetes.io/version: latest
    spec:
      containers:
      - args:
        - -log.level=debug
        env:
        - name: JAEGER_AGENT_HOST
          value: tempo.tempo.svc
        - name: JAEGER_TAGS
          value: namespace=tns
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        image: grafana/tns-db:latest
        name: tns-db
        ports:
        - containerPort: 80
          name: http-metrics
        resources: {}
      serviceAccountName: tns-db
