apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: loadgen
    app.kubernetes.io/instance: tns-loadgen
    app.kubernetes.io/name: tns-loadgen
    app.kubernetes.io/version: latest
  name: tns-loadgen
  namespace: tns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: loadgen
      app.kubernetes.io/instance: tns-loadgen
      app.kubernetes.io/name: tns-loadgen
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: loadgen
        app.kubernetes.io/instance: tns-loadgen
        app.kubernetes.io/name: tns-loadgen
        app.kubernetes.io/version: latest
    spec:
      containers:
      - args:
        - -log.level=debug
        - http://tns-app
        env:
        - name: JAEGER_AGENT_HOST
          value: tempo.tempo.svc
        - name: JAEGER_TAGS
          value: namespace=tns
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        image: grafana/tns-loadgen:latest
        name: tns-app
        ports:
        - containerPort: 80
          name: http-metrics
        resources: {}
      serviceAccountName: tns-loadgen
