apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 0.7.0
  name: tempo
  namespace: tempo
spec:
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: jaeger-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
